check for internet before yle-dl run

diff --git a/muumi-dl b/muumi-dl
--- a/muumi-dl
+++ b/muumi-dl
@@ -27,6 +27,7 @@ muumidir-symlink() {
 # check if areena is available by downloading robots.txt
 # returns 0 for SUCCESS
 check-for-areena() {
+	echo debug: check-for-areena
 	curl -fs "areena.yle.fi/robots.txt" > /dev/null
 }
 
@@ -40,12 +41,16 @@ check-if-new() {
 
 # notify a message with title (which is also echoed)
 # uses growlnotify on OS X and TODO on linux
-# usage: echo "message" | notify areena-url "title"
+# usage: echo "message" | notify [-d areena-url] "title"
 notify() {
-	url="$1"
-	shift
+	[ "$1" == "-d" ] && {
+		id=$2
+		shift 2
+	} || id=muumi-dl
+
 	echo "$@"
-	[ -x $growlnotify ] && $growlnotify -n muumi-dl -d $url "$@"
+
+	[ -x $growlnotify ] && $growlnotify -n muumi-dl -d $id "$@"
 }
 
 # DO THE YLE DL!
@@ -58,17 +63,17 @@ do-yle-dl() {
 	# default destination to desktop
 	destdir=${2:-~/Desktop}
 
-	echo $1 | notify $1 "muumi-dl getting stuff…"
+	echo $1 | notify -d $1 "muumi-dl getting stuff…"
 
 	# TODO: --resume doesn't work, a bug in yle-dl?
 	# tee inside process substitution so we can use yle-dl exit code
 	$yledl --resume --latestepisode --destdir $destdir $1 2> >(tee $muumitemp >> $muumilog) && {
 		check-if-new $muumitemp && {
-			tail -2 $muumitemp | sed G | notify $1 "muumi-dl ok & HAVE NEW STUFF!"
+			tail -2 $muumitemp | sed G | notify -d $1 "muumi-dl ok & HAVE NEW STUFF!"
 		} || {
-			tail -3 $muumitemp | sed G | notify $1 "muumi-dl ok (no new stuff)"
+			tail -3 $muumitemp | sed G | notify -d $1 "muumi-dl ok (no new stuff)"
 		}
-	} || tail -4 $muumitemp | sed G | notify $1 "muumi-dl FAIL :/"
+	} || tail -4 $muumitemp | sed G | notify -d $1 "muumi-dl FAIL :/"
 }
 
 #################### THIS IS OUR CONFIGURATION ####################
@@ -90,10 +95,20 @@ growlnotify=/usr/local/bin/growlnotify
 
 #################### BEGIN MAIN STUFF ####################
 
+date >> $muumilog
+
+echo "checking for areena.yle.fi" | notify "muumi-dl igniting…"
+
 # strip empty lines and #comments (note verbatim tab in sed expression)
 sed 's/#.*//; /^[ 	]*$/d;' $muumilist | while read muumihaku hakemisto; do
 
-	date >> $muumilog	
+	# check for internet twice, then give up
+	check-for-areena || check-for-areena || {
+		echo "muumi-dl can't connect to areena.yle.fi, maybe you have no internet?" \
+			| notify "muumi-dl error :/"
+		exit 2
+	}
+
 	do-yle-dl "$muumihaku" "$hakemisto"
 
 done
